core-identity-uri: ${SERVICE_SCHEME}://${CORE_IDENTITY_HOST}:${CORE_IDENTITY_PORT}

server:
  port: ${CORE_GATEKEEPER_PORT}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER}/oauth2/jwks
          issuer-uri: ${AUTH_SERVER}
  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=gatekeeper
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_schema: gatekeeper
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: gatekeeper
    table: flyway_gatekeeper_history
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /api/gatekeeper/v3/api-docs
  swagger-ui:
    csrf:
      enabled: true
    enabled: true
    path: /api/gatekeeper/swagger-ui.html


langchain4j:
  vertex-ai:
    chat:
      api-key: ${GOOGLE_CLOUD_API_KEY}
      publisher: google
      model-name: ${GOOGLE_MODEL_NAME}
      temperature: 0.7
      max-output-tokens: 2048
      top-k: 40
      top-p: 0.95

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:INFO}
    com.ginkgooai: ${LOG_LEVEL_GINKGOOAI:DEBUG}